name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the project? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or improved?
      placeholder: Describe your idea...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What part of the project does this relate to?
      options:
        - Scripts (new automation)
        - Documentation
        - Hardware support
        - Performance tuning
        - Ceph configuration
        - Network topology
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful? Who would benefit?
      placeholder: Explain the problem this would solve...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Any ideas on how this could work? (optional)
    validations:
      required: false

  - type: input
    id: hardware
    attributes:
      label: Hardware Context
      description: If this relates to specific hardware, what are you using?
      placeholder: e.g., MS-01, Intel NUC 13 Pro, custom server
    validations:
      required: false
